### Please Read the Question carefully and write the code.

1. Input a List from user and convert the list to a numpy array.

In [9]:
import numpy as np

#Technique 1
l = []
while True:
  i = input("Insert only integar numbers: ")
  if i == 'done':
    break
  try:
    i = int(i)
    l.append(i)
  except:
    print("Insert only integar numbers")
    continue
print('\n')
print('Technique 1 output')
print('\n')
print("The given list is =",l)
arr = np.array(l)
print("Converted array =",arr)

print('\n')

#Technique 2

l = []
while True:
  i = input("Insert only integar numbers: ")
  if i == 'done':
    break 
  if i.isdigit() == True:
    i = int(i)
    l.append(i)
  else:
    print('Insert only integar numbers')
print('\n')
print('Technique 2 output')
print('\n')
print("The given list is =",l)
arr = np.array(l)
print("Converted array =",arr)

print('\n')

#Technique 3

l = []
a = 0
i = int(input("What will be the list length?: "))
while a <i:
  z = int(input("Insert number: "))
  l.append(z)
  a += 1
print('\n')
print('Technique 3 output')
print('\n')
print("The given list is =",l)
arr = np.array(l)
print("Converted array =",arr)

Insert only integar numbers: 1
Insert only integar numbers: 2
Insert only integar numbers: done


Technique 1 output


The given list is = [1, 2]
Converted array = [1 2]


Insert only integar numbers: 1
Insert only integar numbers: 2
Insert only integar numbers: done


Technique 2 output


The given list is = [1, 2]
Converted array = [1 2]


What will be the list length?: 1
Insert number: 5


Technique 3 output


The given list is = [5]
Converted array = [5]


2. Create a 4 X 4 identity matrix using numpy and reshape it into 8 X 2 if possible.

In [10]:
import numpy as np
print('''4*4 identity matrix''')
print('\n')
x = np.eye(4)
print(x)
print('\n')
print('reshaped 8*2 matrix')
print('\n')
y = x.reshape(8,2)
print(y)

4*4 identity matrix


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


reshaped 8*2 matrix


[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


3. Create two numpy array and perform arithmetic operation on it.

In [111]:
import numpy as np
a = np.random.randint(0,10,10)
print('a =',a)
b = np.random.randint(0,10,10)
print('b =',b)
print('\n')
c = a+b
print('addition =',c)
d = a-b
print('subtraction =',d)
e = a*b
print('multiplication e',e)
f = a/b
print('division =',f)
g = a**2
print('square =',g)
h = np.sqrt(g)
print('square root =',h)
i = a%2
print('modulus =',i)

a = [7 8 6 6 0 5 1 5 3 0]
b = [4 0 2 4 6 4 1 6 7 5]


addition = [11  8  8 10  6  9  2 11 10  5]
subtraction = [ 3  8  4  2 -6  1  0 -1 -4 -5]
multiplication e [28  0 12 24  0 20  1 30 21  0]
division = [1.75              inf 3.         1.5        0.         1.25
 1.         0.83333333 0.42857143 0.        ]
square = [49 64 36 36  0 25  1 25  9  0]
square root = [7. 8. 6. 6. 0. 5. 1. 5. 3. 0.]
modulus = [1 0 0 0 0 1 1 1 1 0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in true_divide
  del sys.path[0]


4. Find the elements that are multiple of 3 as well as divisable by 5 from a numpy array.

In [15]:
import numpy as np

#Technique 1

a = np.arange(0,50)
print('array =', a)
print('\n')
i = 0
b = len(a)
print('Technique 1 output')
print('\n')
while i <= b:
  if (3*i in a) and ((3*i)%5==0):
    print(3*i, end =' ')
  i+=1
print('\n')

#Technique 2

a = np.arange(0,50)
print('array =', a)
print('\n')
print('Technique 2 output')
print('\n')
for i in a:
  if (i%3 == 0) and (i%5==0):
    print(i, end =' ')

array = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Technique 1 output


0 15 30 45 

array = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Technique 2 output


0 15 30 45 

5. Create a new array from a given array, swapping first and last, second and third columns

In [17]:
import numpy as np

#Swapping columns
print("Swappping columns",'\n')
a = np.random.randint(0,20,(4,4))
print('initial array','\n')
print(a)
print('new sorted array','\n')
a[:,[0,3]]=a[:,[3,0]]
a[:,[1,2]]=a[:,[2,1]]
print(a)

#Swapping rows
print("Swappping rows",'\n')
a = np.random.randint(0,20,(4,4))
print('initial array','\n')
print(a)
print('new sorted array','\n')
b = a[0]
c = a[1]
d = a[2]
e = a[3]
a = np.concatenate((e,d,c,b))
a = a.reshape(4,4)
print('new sorted array','\n')
print(a)

Swappping columns 

initial array 

[[ 0  1 19 12]
 [14  5 18  9]
 [14 19  9  2]
 [12  5  0  5]]
new sorted array 

[[12 19  1  0]
 [ 9 18  5 14]
 [ 2  9 19 14]
 [ 5  0  5 12]]
Swappping rows 

initial array 

[[13  8  0 15]
 [ 7  8  6 15]
 [10 14 19 14]
 [12 19 13  1]]
new sorted array 

new sorted array 

[[12 19 13  1]
 [10 14 19 14]
 [ 7  8  6 15]
 [13  8  0 15]]


6. Multiply a 4x3 matrix by a 3x3 matrix (first check the multipication is possible or not)

In [36]:
print('''4*3 = 12 & 3*3=9. 
As 12 != 9, The multiplication is not possible. ''')

4*3 = 12 & 3*3=9. 
As 12 != 9, The multiplication is not possible. 


7. Create a 6 X 6 matrix and cut the lower 3 X 3 matrix from the biggest one.

In [43]:
import numpy as np
a = np.random.randint(1,20,(6,6))
print('initial matrix','\n')
print(a)
print('\n')
print('lower 3*3 snippet of the initial matrix','\n')
x = a[3:6,3:6]
print(x)

initial matrix 

[[ 8  6  1 11 18  9]
 [11 13  8 14 18 11]
 [ 9 18 17 11 12  3]
 [18 12  4  1  7 14]
 [15 17 12 15  3  2]
 [18 10 14 16 14 13]]


lower 3*3 snippet of the initial matrix 

[[ 1  7 14]
 [15  3  2]
 [16 14 13]]


8. Take a 2D numpy array and sort it in assending and dissending order.

In [19]:
import numpy as np

a = np.random.randint(0,20,(4,5))
print('initial matrix','\n')
print(a,'\n')

b = a[0]
c = a[1]
d = a[2]
e = a[3]
f = np.concatenate((b,c,d,e))
g = np.sort(f)
i = g.reshape(4,5)
print('New array in ascending order:','\n')
print(i)
print('\n')
h = g[::-1]
j = h.reshape(4,5)
print('New array in dscending order:','\n')
print(j)

initial matrix 

[[16  7 18  5  7]
 [10  3 12 14 18]
 [12  6 12 15 11]
 [ 1 18  5 14 10]] 

New array in ascending order: 

[[ 1  3  5  5  6]
 [ 7  7 10 10 11]
 [12 12 12 14 14]
 [15 16 18 18 18]]


New array in dscending order: 

[[18 18 18 16 15]
 [14 14 12 12 12]
 [11 10 10  7  7]
 [ 6  5  5  3  1]]


9. Convert a Python dictionary to Numpy array.

In [25]:
import numpy as np

#Technique 1

d = {'a':6, 'b':5, 'c':4, 'd':3, 'e':2, 'f':1}
l = list(d.items())
x = []
for i in l:
  l =list(i)
  x = np.concatenate((x,l))
print('Technique 1 output','\n')
x = x.reshape(6,2)
print(x)

#Technique 2

d = {'a':6, 'b':5, 'c':4, 'd':3, 'e':2, 'f':1}
l = list(d.items())
x = np.array(l)
print('\n')
print('Technique 2 output','\n')
print(x)

Technique 1 output 

[['a' '6']
 ['b' '5']
 ['c' '4']
 ['d' '3']
 ['e' '2']
 ['f' '1']]


Technique 2 output 

[['a' '6']
 ['b' '5']
 ['c' '4']
 ['d' '3']
 ['e' '2']
 ['f' '1']]


10. Write a code that show all the numpy array generation procedure.

In [26]:
import numpy as np
import matplotlib.pyplot as plt

print('np.arange','\n')
a = np.arange(0,10)
print(a,'\n')

print('multidimensional np.arange','\n')
a = np.arange(0,10).reshape(2,5)
print(a,'\n')

print('\n')

print('randomly array creation','\n')
a = np.random.randint(0,10,10)
print(a,'\n')

print('multidimensional random array creation','\n')
a = np.random.randint(0,10,10).reshape(2,5)
print(a,'\n')

print('\n')

l = list(range(0,10))
print('list =',l,'\n')
print('converting a list into array','\n')
a = np.array(l)
print(a,'\n')

print('converting a list into a multidimentional array','\n')
a = np.array(l).reshape(2,5)
print(a,'\n')

print('\n')

print('only zeros','\n')
a = np.zeros(6)
print(a,'\n')

print('\n')

print('only ones','\n')
a = np.ones(6)
print(a,'\n')

print('\n')

print('generating an identity matrix','\n')
a = np.eye(3)
print(a,'\n')

print('\n')

print('Generating customized diagonal identity matrix','\n')
a = np.diag([1,2,5])
print(a,'\n')

print('\n')

print('using linspace','\n')
a = np.linspace(0,10,5)
print(a,'\n')
print('\n')

print('using logspace','\n')
x = np.linspace(1,2,5)
print('linspace_array,x =',x,'\n')
y = np.logspace(1,2,5)
print('logspace_array,x =',y,'\n')

np.arange 

[0 1 2 3 4 5 6 7 8 9] 

multidimensional np.arange 

[[0 1 2 3 4]
 [5 6 7 8 9]] 



randomly array creation 

[3 7 0 6 7 5 8 6 2 5] 

multidimensional random array creation 

[[5 8 3 0 0]
 [0 4 0 8 5]] 



list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

converting a list into array 

[0 1 2 3 4 5 6 7 8 9] 

converting a list into a multidimentional array 

[[0 1 2 3 4]
 [5 6 7 8 9]] 



only zeros 

[0. 0. 0. 0. 0. 0.] 



only ones 

[1. 1. 1. 1. 1. 1.] 



generating an identity matrix 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



Generating customized diagonal identity matrix 

[[1 0 0]
 [0 2 0]
 [0 0 5]] 



using linspace 

[ 0.   2.5  5.   7.5 10. ] 



using logspace 

linspace_array,x = [1.   1.25 1.5  1.75 2.  ] 

logspace_array,x = [ 10.          17.7827941   31.6227766   56.23413252 100.        ] 

